auth:
  provider: none
components:
  auto_discovery:
    enabled: true
    ignore_patterns:
    - __pycache__
    - '*.pyc'
    - __init__.py
    scan_directories:
    - tools
    - resources
    - prompts
  tools:
  - description: 'MCP Inspector Tools

      Professional MCP server testing and inspection tools'
    module: tools/mcp_inspector_tools.py
    enabled: true
  resources:
  - description: 'MCP Inspector Resources

      Essential documentation and repository information resources'
    module: resources/mcp_inspector_resources.py
    enabled: true
  prompts:
  - description: 'MCP Inspector Guidance Prompts

      Professional guidance system for MCP server inspection workflows'
    module: prompts/inspector_guidance.py
    enabled: true
management:
  expose_management_tools: true
mcpServers: {}
middleware: []
server:
  instructions: This is mcp-inspector-server - MCP server inspection and diagnostic
    tool for analyzing MCP server capabilities, configuration, and runtime status
  name: mcp-inspector-server
transport:
  host: localhost
  log_level: DEBUG
  port: 8000
  transport: stdio
